Домашнє завдання модуль 1
Кравченко Сергій

In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [76]:
v1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=float)
print('Вектор:\n', v1)

Вектор:
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [74]:
m2 = np.zeros((3, 3), dtype=int)
print('Матриця 3х3:\n', m2)

Матриця 3х3:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [73]:
m3 = np.random.randint(1, 11, size=(5, 5))
print('Масив 5х5:\n', m3)

Масив 5х5:
 [[ 7  1  9 10  1]
 [ 3  9 10  8  6]
 [ 9 10  1  5  9]
 [ 6  3  4  9  9]
 [ 1  1  8  6  5]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [72]:
m4 = np.random.random((4, 4))
print('Масив 4х4:\n', m4)

Масив 4х4:
 [[0.67576071 0.16010855 0.41066392 0.12128792]
 [0.67911511 0.76888099 0.54431919 0.48809462]
 [0.63928257 0.92639052 0.11124199 0.62681367]
 [0.15889562 0.53682492 0.69880417 0.03596906]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [71]:
m5_1 = np.random.randint(1, 11, size=5)
m5_2 = np.random.randint(1, 11, size=5)
result_add = m5_1 + m5_2
result_sub = m5_1 - m5_2
result_mul = m5_1 * m5_2
print('Вектор1:\n', m5_1)
print('вектор2:\n', m5_2)
print('Результат додавання векторів:\n', m5_1 + m5_2)
print('Результат віднімання векторів:\n', m5_1 - m5_2)
print('Результат множення векторів:\n', m5_1 * m5_2)

Вектор1:
 [3 2 6 6 1]
вектор2:
 [7 4 3 4 1]
Результат додавання векторів:
 [10  6  9 10  2]
Результат віднімання векторів:
 [-4 -2  3  2  0]
Результат множення векторів:
 [21  8 18 24  1]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [69]:
m6_1 = np.array([10, 22, 3, 6, 8, 14, -6])
m6_2 = np.array([-4, 5, 6, 8, 45, 7, 5])
print('Вектор1:\n', m6_1)
print('вектор2:\n', m6_2)
print('Скалярний добуток векторів:\n', np.dot(m6_1,  m6_2))

Вектор1:
 [10 22  3  6  8 14 -6]
вектор2:
 [-4  5  6  8 45  7  5]
Скалярний добуток векторів:
 564


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [67]:
m7_1 = np.random.randint(1, 11, size=(2, 2))
m7_2 = np.random.randint(1, 11, size=(2, 3))
print('Матриця1:\n', m7_1)
print('Матриця2:\n', m7_2)
print('Результат перемноження:\n',np.dot(m7_1, m7_2))

Матриця1:
 [[7 9]
 [8 8]]
Матриця2:
 [[9 1 6]
 [4 7 2]]
Результат перемноження:
 [[ 99  70  60]
 [104  64  64]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [66]:
m8 = np.random.randint(1, 11, size=(3, 3))
print('Матриця:\n', m8)
print('Обернена матриця: \n', np.linalg.inv(m8))

Матриця:
 [[ 6 10  5]
 [ 5 10 10]
 [ 2  8  7]]
Обернена матриця: 
 [[ 0.09090909  0.27272727 -0.45454545]
 [ 0.13636364 -0.29090909  0.31818182]
 [-0.18181818  0.25454545 -0.09090909]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [27]:
m9 = np.random.random((4, 4))
print('Матриця:\n', m9)
print('Транспонована матриця:\n', m9.T)

Матриця:
 [[0.97059318 0.99998507 0.69849524 0.40794627]
 [0.50078391 0.67784147 0.31503894 0.54107461]
 [0.54212481 0.53635876 0.63659153 0.37868184]
 [0.60273806 0.64481802 0.87137145 0.97634072]]
Транспонована матриця:
 [[0.97059318 0.50078391 0.54212481 0.60273806]
 [0.99998507 0.67784147 0.53635876 0.64481802]
 [0.69849524 0.31503894 0.63659153 0.87137145]
 [0.40794627 0.54107461 0.37868184 0.97634072]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [30]:
m10 = np.random.randint(1, 11, size=(3, 4))
v10 = np.random.randint(1, 11, size=(4,))
print('Матриця:\n', m10)
print('Вектор:\n', v10)
print('Результат множення матриці на вектор:\n', np.dot(m10, v10))

Матриця:
 [[4 1 5 9]
 [4 7 6 1]
 [2 8 3 8]]
Вектор:
 [10  5 10  9]
Результат множення матриці на вектор:
 [176 144 162]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [32]:
m11 = np.random.random((2, 3))
v11 = np.random.random((3, ))
print('Матриця:\n', m11)
print('Вектор:\n', v11)
print('Результат множення матриці на вектор:\n', np.dot(m11, v11))

Матриця:
 [[0.92934963 0.04839507 0.66155998]
 [0.85011645 0.51489242 0.27868051]]
Вектор:
 [0.42412276 0.57689277 0.05843816]
Результат множення матриці на вектор:
 [0.46073745 0.67387703]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [42]:
m12_1 = np.random.randint(1, 11, size=(2, 2))
m12_2 = np.random.randint(1, 11, size=(2, 2))
print('Матриця1:\n', m12_1)
print('Матриця2:\n', m12_2)
print('Результат множення матриць:\n', np.multiply(m12_1, m12_2))

Матриця1:
 [[4 7]
 [7 5]]
Матриця2:
 [[ 8  2]
 [ 9 10]]
Результат множення матриць:
 [[32 14]
 [63 50]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [43]:
m13_1 = np.random.randint(1, 11, size=(2, 2))
m13_2 = np.random.randint(1, 11, size=(2, 2))
print('Матриця1:\n', m13_1)
print('Матриця2:\n', m13_2)
print('Результат добутку матриць:\n', np.dot(m13_1, m13_2))

Матриця1:
 [[5 4]
 [9 9]]
Матриця2:
 [[7 1]
 [7 4]]
Результат добутку матриць:
 [[ 63  21]
 [126  45]]


14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [63]:
m14 = np.random.randint(1, 101, size=(5, 5))
print('Матриця:\n', m14)
print('Сума елементів матриці:\n', np.sum(m14))

Матриця:
 [[74 75 99 49 60]
 [67 94 37 18  4]
 [55 40 73 26  4]
 [36 78  7 90 17]
 [16 66 68 25 38]]
Сума елементів матриці:
 1216


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [46]:
m15_1 = np.random.randint(1, 11, size=(4, 4))
m15_2 = np.random.randint(1, 11, size=(4, 4))
print('Матриця1:\n', m15_1)
print('Матриця2:\n', m15_2)
print('Результат різниці матриць:\n', m15_1 - m15_2)

Матриця1:
 [[10  8  9  9]
 [ 6  1  6  3]
 [ 5  9  4  5]
 [10  4  8  4]]
Матриця2:
 [[4 3 8 8]
 [3 1 2 1]
 [8 4 6 6]
 [2 7 7 1]]
Результат різниці матриць:
 [[ 6  5  1  1]
 [ 3  0  4  2]
 [-3  5 -2 -1]
 [ 8 -3  1  3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [62]:
m16 = np.random.random((3, 3))
print('Матриця:\n', m16)
print('Вектор-стовпчик:\n', m16.sum(axis=1).reshape(-1, 1))

Матриця:
 [[0.36638779 0.1456456  0.5847481 ]
 [0.16712509 0.2854094  0.0176206 ]
 [0.12204173 0.55358878 0.92489823]]
Вектор-стовпчик:
 [[1.09678148]
 [0.47015508]
 [1.60052875]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [61]:
m17 = np.random.randint(1, 31, size=(3, 4))
print('Матриця:\n', m17)
print('Матриця квадратів:\n', np.power(m17,2))

Матриця:
 [[17 27 13  4]
 [26 11 24 26]
 [12 12 25  4]]
Матриця квадратів:
 [[289 729 169  16]
 [676 121 576 676]
 [144 144 625  16]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [60]:
m18 = np.random.randint(1, 51, size=(4, ))
print('Вектор:\n', m18)
print('Вектор коренів:\n', np.power(m18,0.5))

Вектор:
 [19  1  5 42]
Вектор коренів:
 [4.35889894 1.         2.23606798 6.4807407 ]
